"""create accreditation cycles

Revision ID: c6b94a13a148
Revises: 2c78e5f36813
Create Date: 2026-09-12 22:44:46.235543

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6b94a13a148'
down_revision: Union[str, Sequence[str], None] = '2c78e5f36813'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accreditation_cycles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('institution_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('academic_period', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_accreditation_cycles_code'), 'accreditation_cycles', ['code'], unique=True)
    op.create_index(op.f('ix_accreditation_cycles_id'), 'accreditation_cycles', ['id'], unique=False)
    op.create_index(op.f('ix_accreditation_cycles_institution_id'), 'accreditation_cycles', ['institution_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_accreditation_cycles_institution_id'), table_name='accreditation_cycles')
    op.drop_index(op.f('ix_accreditation_cycles_id'), table_name='accreditation_cycles')
    op.drop_index(op.f('ix_accreditation_cycles_code'), table_name='accreditation_cycles')
    op.drop_table('accreditation_cycles')
    # ### end Alembic commands ###
